# Generated by Django 4.2.1 on 2023-11-14 23:12

import core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('cash', 'Cash'), ('equity', 'Equity'), ('crypto', 'Crypto'), ('fund', 'Fund'), ('other', 'Other')], default='cash', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=12, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicIndex',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daily_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('weekly_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monthly_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('yearly_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('decennial_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default=core.models.default_wallet_name, max_length=200)),
                ('provider', models.CharField(default='', max_length=48)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=19)),
                ('input_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=19)),
                ('is_public', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_asset', to='core.asset')),
                ('input_asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_input_asset', to='core.asset')),
            ],
        ),
        migrations.AddField(
            model_name='keibouser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keibouser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='keibouser',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='keibouser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='keibouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='keibouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Manager'), (4, 'Owner')])),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wallet', to='core.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=32)),
                ('counterparty', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=19)),
                ('disposable', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wallet', to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Manager'), (4, 'Owner')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wallet', to='core.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
