# Generated by Django 4.2.1 on 2023-08-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_economicindex_wallet_keibouser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
