# Generated by Django 4.2.1 on 2023-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keibouser_groups_keibouser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keibouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
