# Generated by Django 4.2.1 on 2023-09-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_economicindex_wallet_walletprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='category',
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('cash', 'Cash'), ('equity', 'Equity'), ('crypto', 'Crypto'), ('fund', 'Fund'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='provider',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.DeleteModel(
            name='WalletProvider',
        ),
    ]
