# Generated by Django 4.2.1 on 2023-12-15 16:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPNLTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=19)),
                ('average_purchase_ratio', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=19)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_asset', to='core.asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_wallet', to='core.wallet')),
            ],
        ),
    ]
