# Generated by Django 4.2.1 on 2023-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallet_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
