# Generated by Django 4.2.1 on 2023-12-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_walletpnltracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='input_amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='input_asset',
        ),
    ]
