# Generated by Django 4.2.1 on 2023-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_wallet_input_amount_remove_wallet_input_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='keibouser',
            name='is_prime_user',
            field=models.BooleanField(default=False),
        ),
    ]
