# Generated by Django 4.2.1 on 2023-12-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_keibouser_is_prime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='counterparty',
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_of_origin', to='core.transaction'),
        ),
    ]
