# Generated by Django 4.2.1 on 2023-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_walletuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='provider',
            field=models.CharField(default='credit-agricole', max_length=24),
            preserve_default=False,
        ),
    ]
