# Generated by Django 4.2.1 on 2023-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wallet_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
