# Generated by Django 4.2.1 on 2023-08-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daily_delta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weekly_delta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('monthly_delta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('yearly_delta', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
