# Generated by Django 4.2.1 on 2023-08-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_index_daily_delta_alter_index_monthly_delta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='EconomicIndex',
        ),
    ]
