# Generated by Django 4.2.1 on 2023-08-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_index_economicindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicindex',
            name='decennial_delta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
